#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
}
task go()
{
	motor[frontLeft] = vexRT[Ch3];
	motor[backLeft] = vexRT[Ch3];
	motor[frontRight] = vexRT[Ch2];
	motor[backRight] = vexRT[Ch2];
}
task usercontrol()
{
	startTask(go);
	while (true)
	{ 
		wait1Msec (1);
	}
}
