#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port2,           LF,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LB,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           RF,            tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           RB,            tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
}

task usercontrol()
{

	while (true)
	{

		motor[LF] = vexRT[Ch3];
		motor[LB] = vexRT[Ch3];
		motor[RF] = vexRT[Ch2];
		motor[RB] = vexRT[Ch2];
	}
}
